* Appendix A: Installation Details

** Basic Installation with Homebrew

   I'm not very good at Emacs, and I don't have the much experience
   with using Emacs on MacOS. That said, I get up and running with
   Emacs using the brew based installation with:

#+begin_src shell-script :tangle no
  brew install emacs --cocoa
#+end_src

   This takes some time to complete, and when you're done, you've got
   to take one more step in order to make Emacs appear in your
   Applications list:

#+begin_src shell-script :tangle no
  ln -s /usr/local/Cellar/emacs/24.3/Emacs.app /Applications
#+end_src

** Installing Emacs Starter Kit

   Once I've got a basic Emacs running, my first step is to install
   the Emacs Starter Kit. When present, this helpful framework loads
   up the Emacs Lisp for customization thats embedded in this
   document. To get Emacs Starter Kit
   Once I was running emacs, I switched to the *scratch* buffer and
   copy-and-pasted the following elisp in:

#+begin_src emacs-lisp :tangle no
  (package-initialize)

  (add-to-list 'package-archives
    '("melpa" . "http://melpa.milkbox.net/packages/") t)

  (package-list-packages)
#+end_src

  Once this is in your *scratch* buffer (or any other buffer.. emacs
  doesn't care) you can move your cursor past the closing parens in
  each of these statements and press C-x C-e.

  Doing this will cause Emacs to "look backwards" to the last set of
  parens and execute the code there.

  These specific lines initialize the package management system,
  temporarily add well-known repository to that system, and then
  start the package manager within Emacs.

  I installed ESK by searching down to find 'starter-kit,' pressing
  'i' to mark it for installation, and then pressing 'x' to execute
  on my installation instructions.

** Details Concerning .el generation from .org files

  The following elisp defines which .org files are in my
  configuration:

#+begin_src emacs-lisp :tangle no
  (setq jedcn-config-files '("general-setup.org"
                             "personal-information.org"
                             "key-bindings.org"
                             "behaviors.org"
                             "modes.org"
                             "various-and-sundry.org"))
#+end_src

  And this function enables you to create .el from .org files:

#+begin_src emacs-lisp :tangle no
  (defun extract-and-load-elisp-from-org (org-file-list)
    "Create and load .el files from .org files named in ORG-FILE-LIST"
    (while org-file-list
      (setq org-file (car org-file-list))
      (org-babel-load-file org-file)
      (setq org-file-list (cdr org-file-list))
      ))
#+end_src

  And, finally, here's an invocation of this function and converts all
  of my .org files (and loads them..)

#+begin_src emacs-lisp :tangle no
  (extract-and-load-elisp-from-org jedcn-config-files)
#+end_src

  Once they've been generated, the .el files will exist and the ESK
  will seek them out and load them as part of its normal start up
  process (presuming they are located at ~/.emacs.d/$USER).
