* Appendix A: Installation Details

  This appendix covers both how I install Emacs on MacOS and how I get
  up and running with =emacs-setup=.

** Emacs Installation

   On MacOS I install Emacs using [[http://brew.sh/][Homebrew]]. I run the following,
   inspired by this [[http://emacsredux.com/blog/2013/08/21/color-themes-redux/][Emacs Redux post on color themes]]:

#+begin_src sh :tangle no
  brew install emacs --cocoa --srgb
#+end_src

   This takes some time to complete, and when finished I take another
   step to make Emacs appear as one of my Applications:

#+begin_src sh :tangle no
  ln -s /usr/local/Cellar/emacs/24.3/Emacs.app /Applications
#+end_src

   Now I can start emacs by selecting it graphically in the
   Applications area.

** Cask Installation

   I then use brew to get cask. Cask handles the fetching and
   installation of packages that I use:

#+begin_src sh :tangle no
  brew install cask
#+end_src

** Using =emacs-setup=

   Once I have Emacs 24+ and cask, I use git to clone my =emacs-setup=
   to my machine, cd into the cloned directory, and source the file
   =install.sh=:

#+begin_src shell-script :tangle no
  git clone https://github.com/jedcn/emacs-setup.git
  cd emacs-setup
  source install.sh
#+end_src

   The contents of the =install.sh= file achieve the following:

   + They allow you to supply a =HOME= and will create an =.emacs.d=
     underneath =HOME= if needed.

   + They create a link within this =.emacs.d= back to the cloned
     =emacs-setup=.

   + They create a Cask file, run a =cask install=. This contacts
     melpa and installs all dependent packages.

   + Finally, they copy a =init.el= into HOME so that the next startup
     of Emacs will load the composite =emacs-setup.el=.

#+begin_src sh :tangle install.sh :padline no
  #!/bin/bash

  emacs_setup_dir=`pwd`

  echo "Creating $HOME/.emacs.d (if needed)"
  mkdir -p $HOME/.emacs.d

  echo "Creating $HOME/.emacs.d/emacs-setup as link to $emacs_setup_dir"
  ln -s $emacs_setup_dir $HOME/.emacs.d/emacs-setup

  echo "Creating $HOME/.emacs.d/init.el"
  BREW_PREFIX=$(brew --prefix)
  CASK_VERSION=$(cask --version)
  CASK_DIR="${BREW_PREFIX}/Cellar/cask/${CASK_VERSION}/"
  echo "(setq jedcn-cask-dir \"${CASK_DIR}\")" > init.el.tmp
  cat init.el >> init.el.tmp
  mv init.el.tmp $HOME/.emacs.d/init.el

  echo "Creating $HOME/.emacs.d/Cask"
  cp Cask $HOME/.emacs.d

  pushd $HOME/.emacs.d
  echo "Installing Packages with Cask"
  cask install
  popd
#+end_src

   It is important to note that =HOME= can be given a temporary value
   and this lets me test my installation process. I can get a fresh
   copy of =emacs-setup= and clone it into a temporary directory, and
   then I can run the =install.sh= with a temporary value of =HOME=
   like so:

#+begin_src sh :tangle no
  mkdir /tmp/emacs-setup && cd /tmp/emacs-setup
  git clone https://github.com/jedcn/emacs-setup.git .

  mkdir /tmp/emacs-home
  HOME=/tmp/emacs-home source install.sh
  HOME=/tmp/emacs-home /Applications/Emacs.app/Contents/MacOS/Emacs &
#+end_src
