* Behaviors

  ...

  be·hav·ior
  /biˈhāvyər/
  Noun

  + The way in which one acts or conducts oneself, esp. toward others:
    "his insulting behavior towards me".

  + The way in which an animal or person acts in response to a
    particular situation or stimulus: "the feeding behavior of
    predators".

  ...

** Miscellaneous

   Do not "ding" all of the time, and instead flash the screen. Do not
   show the Emacs "splash" screen.

#+begin_src emacs-lisp
  (setq visible-bell t
        inhibit-startup-message t)
#+end_src

** Whitespace Cleanup

   The following creates a function that cleans up whitespace, and
   then adds a hook that makes this happen each time you save. It
   comes from a post within "what the emacs.d," specifically titled
   [[http://whattheemacsd.com/buffer-defuns.el-01.html][buffer defuns]].

#+begin_src emacs-lisp
  (defun cleanup-buffer-safe ()
    "Perform a bunch of safe operations on the whitespace content of a buffer."
    (interactive)
    (untabify (point-min) (point-max))
    (delete-trailing-whitespace)
    (set-buffer-file-coding-system 'utf-8))

  (add-hook 'before-save-hook 'cleanup-buffer-safe)
#+end_src

** Yes or No?

   Emacs often asks you to type "yes or no" to proceed. As an example,
   consider when you are in magit, and you press "k" to kill off a
   hunk. I am happy to have a confirmation before something is
   deleted, but I prefer to just press "y" instead of "y-e-s-<RETURN"

#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
** Autofill

   By observation alone, =auto-fill-mode= makes it so that things
   "word wrap." If you go past a certain boundary, and you type a
   space, then the text you are working with wraps to another line. I
   want to auto-fill if I am working on text. When I am programming, I
   only want to auto-fill if I am writing a comment.

   Both of these come from technomancy in v2 of the [[https://github.com/technomancy/emacs-starter-kit][emacs-starter-kit]].

#+begin_src emacs-lisp
  (defun esk-local-comment-auto-fill ()
    (set (make-local-variable 'comment-auto-fill-only-comments) t)
    (auto-fill-mode t))
  (add-hook 'prog-mode-hook 'esk-local-comment-auto-fill)

  (add-hook 'text-mode-hook 'turn-on-auto-fill)
#+end_src
